// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tpaoProjeMvc.Models;

#nullable disable

namespace tpaoProjeMvc.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tpaoProjeMvc.Models.Kuyu", b =>
                {
                    b.Property<int>("KuyuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KuyuId"));

                    b.Property<int?>("SahaId")
                        .HasColumnType("int");

                    b.Property<string>("kuyuAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KuyuId");

                    b.HasIndex("SahaId");

                    b.ToTable("Kuyular");
                });

            modelBuilder.Entity("tpaoProjeMvc.Models.Saha", b =>
                {
                    b.Property<int>("SahaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SahaId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("sahaAdı")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SahaId");

                    b.ToTable("Sahalar");
                });

            modelBuilder.Entity("tpaoProjeMvc.Models.Wellbore", b =>
                {
                    b.Property<int>("WellboreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WellboreId"));

                    b.Property<int>("KuyuId")
                        .HasColumnType("int");

                    b.Property<string>("wellboreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WellboreId");

                    b.HasIndex("KuyuId");

                    b.ToTable("Wellbores");
                });

            modelBuilder.Entity("tpaoProjeMvc.Models.Kuyu", b =>
                {
                    b.HasOne("tpaoProjeMvc.Models.Saha", "Saha")
                        .WithMany("kuyuList")
                        .HasForeignKey("SahaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Saha");
                });

            modelBuilder.Entity("tpaoProjeMvc.Models.Wellbore", b =>
                {
                    b.HasOne("tpaoProjeMvc.Models.Kuyu", "Kuyu")
                        .WithMany("wellbores")
                        .HasForeignKey("KuyuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kuyu");
                });

            modelBuilder.Entity("tpaoProjeMvc.Models.Kuyu", b =>
                {
                    b.Navigation("wellbores");
                });

            modelBuilder.Entity("tpaoProjeMvc.Models.Saha", b =>
                {
                    b.Navigation("kuyuList");
                });
#pragma warning restore 612, 618
        }
    }
}
